micronaut.application.name=vehiculos-api


datasources.default.url=jdbc:h2:mem:devDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
datasources.default.driverClassName=org.h2.Driver
datasources.default.username=sa
datasources.default.password=
datasources.default.schema-generate=CREATE_DROP
datasources.default.dialect=H2


jpa.default.entity-scan-packages=vehiculos.api.clases
jpa.default.properties.hibernate.hbm2ddl.auto=create-drop
jpa.default.properties.hibernate.hbm2ddl.auto=update


jpa.default.properties.hibernate.hbm2ddl.import_files=data.sql




